# -*- coding: utf-8 -*-
"""Random_Graphs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14OyVezIx2UE__9B_QZ9DAXIWr6vWjQ6J
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

# %matplotlib inline

def all_pairs(nodes):
    for i,u in enumerate(nodes):
        for j,v in enumerate(nodes):
            if i>j:
                yield u,v

def random_pairs(nodes,p):
    for edge in all_pairs(nodes):
        if flip(p):
            yield edge

def flip(p):
    return np.random.random() < p

def make_random_graph(n,p):
    G = nx.Graph()
    nodes=range(n)
    G.add_nodes_from(nodes)
    G.add_edges_from(random_pairs(nodes,p))
    return G

my_random_graph = make_random_graph(30,0.5)

nx.draw_circular(my_random_graph,node_size=200, with_labels=True)

